# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [14]:
# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7,7)
tensor1

tensor([[0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047, 0.1100],
        [0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237, 0.4910],
        [0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967, 0.1957],
        [0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186],
        [0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748],
        [0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743, 0.4743],
        [0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179, 0.9736]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [15]:
# Create another random tensor
tensor2 = torch.rand(1,7).reshape(7,1) # or use the torch.transpose(input,dim1,dim2)
# Perform matrix multiplication
matrix0 = torch.matmul(tensor1,tensor2)
matrix0

tensor([[2.1422],
        [1.8840],
        [1.3052],
        [2.5827],
        [1.6046],
        [1.1300],
        [2.7294]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor3 = torch.rand(7,7)
tensor4 = torch.rand(1,7).transpose(0,1)
# tensor4 = torch.transpose(tensor4,0,1)
# torch.transpose(tensor4, 0, 1) 和 tensor4.transpose(0, 1) 是等价的，它们的作用完全相同，都是交换张量 tensor4 的第 0 维和第 1 维。

# Matrix multiply tensors
matrix1 = torch.matmul(tensor3,tensor4)
matrix1,matrix1.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [21]:
# Set random seed
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
tensor_gpu1 = torch.rand(2,3).to(device)
tensor_gpu2 = torch.rand(2,3).to(device)
print(f"Device:{device}")
tensor_gpu1,tensor_gpu2

Device:cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [23]:
# Perform matmul on tensor_A and tensor_B
matrix7 = torch.matmul(tensor_gpu1,tensor_gpu2.T)
matrix7,matrix7.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
maxV = torch.max(matrix7)
# Find min
minV = torch.min(matrix7)
maxV,minV

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
maxIndex = torch.argmax(matrix7)

# Find arg min
minIndex = torch.argmin(matrix7)
maxIndex,minIndex

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensorA = torch.rand(1,1,1,10)

# Remove single dimensions
tensorB = torch.squeeze(tensorA)

# Print out tensors and their shapes
tensorA,tensorA.shape,tensorB,tensorB.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))